AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Account 1'
Parameters:
  AccountId0:
    Type: String
  AccountId1:
    Type: String
  AccountId2:
    Type: String

Resources:
  CatUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'CatUser'
      Policies:
        - PolicyName: 'S3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                Resource:
                  - '*'
      Tags:
        - Key: Animal
          Value: Cat

  DogUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'DogUser'
      ManagedPolicyArns:
        - !Ref DogPolicy
      Tags:
        - Key: Animal
          Value: Dog

  DogPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: 'Grants admin access'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: '*'
            Resource: '*'

  FishUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'FishUser'
      Policies:
        - PolicyName: 'FullSNSPermissions'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'sns:*'
                Resource:
                  - '*'
      Tags:
        - Key: Animal
          Value: Fish

  LemurTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: 'LemurTopic'
      Tags:
        - Key: Animal
          Value: Lemur

  LemurTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      Topics:
        - !Ref LemurTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowBlueRole'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AccountId0}:role/BlueRole'
            Action:
              - 'sns:Publish'
            Resource: !GetAtt LemurTopic.TopicArn

