AWSTemplateFormatVersion: '2010-09-09'
Description: 'Resources for test account 0'

Resources:
  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:user/admin'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'S3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - 'arn:aws:s3:::Cyan'
                  - 'arn:aws:s3:::Cyan/*'
                  - 'arn:aws:s3:::Magenta'
                  - 'arn:aws:s3:::Magenta/*'
