// This file was automatically generated by build tooling; do not edit!

package managedpolicies

import (
	"github.com/nsiow/yams/pkg/policy"
)

var AWS_MANAGED_POLICY_AWSPartnerCentralSellingResourceSnapshotJobExecutionRolePolicy = policy.Policy{Version: "2012-10-17", Id: "", Statement: policy.StatementBlock{policy.Statement{Sid: "", Effect: "Allow", Principal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, NotPrincipal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, Action: policy.Value{"partnercentral:CreateResourceSnapshot"}, NotAction: policy.Value(nil), Resource: policy.Value{"arn:aws:partnercentral:*::catalog/AWS/engagement/*", "arn:aws:partnercentral:*::catalog/Sandbox/engagement/*"}, NotResource: policy.Value(nil), Condition: map[string]map[string]policy.Value(nil)}, policy.Statement{Sid: "", Effect: "Allow", Principal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, NotPrincipal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, Action: policy.Value{"partnercentral:GetOpportunity"}, NotAction: policy.Value(nil), Resource: policy.Value{"arn:aws:partnercentral:*:*:catalog/AWS/opportunity/*", "arn:aws:partnercentral:*:*:catalog/Sandbox/opportunity/*"}, NotResource: policy.Value(nil), Condition: map[string]map[string]policy.Value(nil)}}}
