// This file was automatically generated by build tooling; do not edit!

package managedpolicies

import (
	"github.com/nsiow/yams/pkg/policy"
)

var AWS_MANAGED_POLICY_AWSElasticDisasterRecoveryFailbackInstallationPolicy = policy.Policy{Version: "2012-10-17", Id: "", Statement: policy.StatementBlock{policy.Statement{Sid: "DRSFailbackInstallationPolicy1", Principal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, NotPrincipal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, Effect: "Allow", Action: policy.Value{"drs:SendClientLogsForDrs", "drs:SendClientMetricsForDrs", "drs:DescribeRecoveryInstances", "drs:DescribeSourceServers"}, NotAction: policy.Value(nil), Resource: policy.Value{"*"}, NotResource: policy.Value(nil), Condition: policy.ConditionBlock(nil)}, policy.Statement{Sid: "DRSFailbackInstallationPolicy2", Principal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, NotPrincipal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, Effect: "Allow", Action: policy.Value{"drs:TagResource", "drs:IssueAgentCertificateForDrs", "drs:AssociateFailbackClientToRecoveryInstanceForDrs", "drs:GetSuggestedFailbackClientDeviceMappingForDrs", "drs:UpdateAgentReplicationInfoForDrs", "drs:UpdateFailbackClientDeviceMappingForDrs"}, NotAction: policy.Value(nil), Resource: policy.Value{"arn:aws:drs:*:*:recovery-instance/*"}, NotResource: policy.Value(nil), Condition: policy.ConditionBlock(nil)}}}
