// This file was automatically generated by build tooling; do not edit!

package managedpolicies

import (
	"github.com/nsiow/yams/pkg/policy"
)

var AWS_MANAGED_POLICY_AWSDirectoryServiceDataFullAccess = policy.Policy{Version: "2012-10-17", Id: "", Statement: policy.StatementBlock{policy.Statement{Sid: "DSDataFullAccess", Effect: "Allow", Principal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, NotPrincipal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, Action: policy.Value{"ds:AccessDSData", "ds-data:AddGroupMember", "ds-data:CreateGroup", "ds-data:CreateUser", "ds-data:DeleteGroup", "ds-data:DeleteUser", "ds-data:DescribeGroup", "ds-data:DescribeUser", "ds-data:DisableUser", "ds-data:ListGroupMembers", "ds-data:ListGroups", "ds-data:ListGroupsForMember", "ds-data:ListUsers", "ds-data:RemoveGroupMember", "ds-data:SearchGroups", "ds-data:SearchUsers", "ds-data:UpdateGroup", "ds-data:UpdateUser"}, NotAction: policy.Value(nil), Resource: policy.Value{"arn:aws:ds:*:*:directory/*"}, NotResource: policy.Value(nil), Condition: map[string]map[string]policy.Value(nil)}}}
