// This file was automatically generated by build tooling; do not edit!

package managedpolicies

import (
	"github.com/nsiow/yams/pkg/policy"
)

var AWS_MANAGED_POLICY_AWSIdentitySyncFullAccess = policy.Policy{Version: "2012-10-17", Id: "", Statement: policy.StatementBlock{policy.Statement{Sid: "", Principal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, NotPrincipal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, Effect: "Allow", Action: policy.Value{"ds:AuthorizeApplication", "ds:UnauthorizeApplication"}, NotAction: policy.Value(nil), Resource: policy.Value{"arn:*:ds:*:*:*/*"}, NotResource: policy.Value(nil), Condition: policy.ConditionBlock(nil)}, policy.Statement{Sid: "", Principal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, NotPrincipal: policy.Principal{AWS: policy.Value(nil), Federated: policy.Value(nil), Service: policy.Value(nil), CanonicalUser: policy.Value(nil)}, Effect: "Allow", Action: policy.Value{"identity-sync:DeleteSyncProfile", "identity-sync:CreateSyncProfile", "identity-sync:GetSyncProfile", "identity-sync:StartSync", "identity-sync:StopSync", "identity-sync:CreateSyncFilter", "identity-sync:DeleteSyncFilter", "identity-sync:ListSyncFilters", "identity-sync:CreateSyncTarget", "identity-sync:DeleteSyncTarget", "identity-sync:GetSyncTarget", "identity-sync:UpdateSyncTarget"}, NotAction: policy.Value(nil), Resource: policy.Value{"arn:*:identity-sync:*:*:*/*"}, NotResource: policy.Value(nil), Condition: policy.ConditionBlock(nil)}}}
