name: yams Test Suite
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - name: Build
      run: make build
    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.8
    - name: Test
      run: make cov
    - name: Upload
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
